name: call_queue_amazon
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  # flutter_mobile_vision_2: ^0.1.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  external_path: ^2.0.1
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.3
  file_picker: ^8.1.2
  fluttertoast: ^8.2.6
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logoHawkerChan.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sound/TH/TH- (0).mp3
    - assets/sound/TH/TH- (1).mp3
    - assets/sound/TH/TH- (2).mp3
    - assets/sound/TH/TH- (3).mp3
    - assets/sound/TH/TH- (4).mp3
    - assets/sound/TH/TH- (5).mp3
    - assets/sound/TH/TH- (6).mp3
    - assets/sound/TH/TH- (7).mp3
    - assets/sound/TH/TH- (8).mp3
    - assets/sound/TH/TH- (9).mp3
    - assets/sound/TH/TH- (10).mp3
    - assets/sound/TH/TH- (11).mp3
    - assets/sound/TH/TH- (12).mp3
    - assets/sound/TH/TH- (13).mp3
    - assets/sound/TH/TH- (14).mp3
    - assets/sound/TH/TH- (15).mp3
    - assets/sound/TH/TH- (16).mp3
    - assets/sound/TH/TH- (17).mp3
    - assets/sound/TH/TH- (18).mp3
    - assets/sound/TH/TH- (19).mp3
    - assets/sound/TH/TH- (20).mp3
    - assets/sound/TH/TH- (21).mp3
    - assets/sound/TH/TH- (22).mp3
    - assets/sound/TH/TH- (23).mp3
    - assets/sound/TH/TH- (24).mp3
    - assets/sound/TH/TH- (25).mp3
    - assets/sound/TH/TH- (26).mp3
    - assets/sound/TH/TH- (27).mp3
    - assets/sound/TH/TH- (28).mp3
    - assets/sound/TH/TH- (29).mp3
    - assets/sound/TH/TH- (30).mp3
    - assets/sound/TH/TH- (31).mp3
    - assets/sound/TH/TH- (32).mp3
    - assets/sound/TH/TH- (33).mp3
    - assets/sound/TH/TH- (34).mp3
    - assets/sound/TH/TH- (35).mp3
    - assets/sound/TH/TH- (36).mp3
    - assets/sound/TH/TH- (37).mp3
    - assets/sound/TH/TH- (38).mp3
    - assets/sound/TH/TH- (39).mp3
    - assets/sound/TH/TH- (40).mp3
    - assets/sound/TH/TH- (41).mp3
    - assets/sound/TH/TH- (42).mp3
    - assets/sound/TH/TH- (43).mp3
    - assets/sound/TH/TH- (44).mp3
    - assets/sound/TH/TH- (45).mp3
    - assets/sound/TH/TH- (46).mp3
    - assets/sound/TH/TH- (47).mp3
    - assets/sound/TH/TH- (48).mp3
    - assets/sound/TH/TH- (49).mp3
    - assets/sound/TH/TH- (50).mp3
    - assets/sound/TH/TH- (51).mp3
    - assets/sound/TH/TH- (52).mp3
    - assets/sound/TH/TH- (53).mp3
    - assets/sound/TH/TH- (54).mp3
    - assets/sound/TH/TH- (55).mp3
    - assets/sound/TH/TH- (56).mp3
    - assets/sound/TH/TH- (57).mp3
    - assets/sound/TH/TH- (58).mp3
    - assets/sound/TH/TH- (59).mp3
    - assets/sound/TH/TH- (60).mp3
    - assets/sound/TH/TH- (61).mp3
    - assets/sound/TH/TH- (62).mp3
    - assets/sound/TH/TH- (63).mp3
    - assets/sound/TH/TH- (64).mp3
    - assets/sound/TH/TH- (65).mp3
    - assets/sound/TH/TH- (66).mp3
    - assets/sound/TH/TH- (67).mp3
    - assets/sound/TH/TH- (68).mp3
    - assets/sound/TH/TH- (69).mp3
    - assets/sound/TH/TH- (70).mp3
    - assets/sound/TH/TH- (71).mp3
    - assets/sound/TH/TH- (72).mp3
    - assets/sound/TH/TH- (73).mp3
    - assets/sound/TH/TH- (74).mp3
    - assets/sound/TH/TH- (75).mp3
    - assets/sound/TH/TH- (76).mp3
    - assets/sound/TH/TH- (77).mp3
    - assets/sound/TH/TH- (78).mp3
    - assets/sound/TH/TH- (79).mp3
    - assets/sound/TH/TH- (80).mp3
    - assets/sound/TH/TH- (81).mp3
    - assets/sound/TH/TH- (82).mp3
    - assets/sound/TH/TH- (83).mp3
    - assets/sound/TH/TH- (84).mp3
    - assets/sound/TH/TH- (85).mp3
    - assets/sound/TH/TH- (86).mp3
    - assets/sound/TH/TH- (87).mp3
    - assets/sound/TH/TH- (88).mp3
    - assets/sound/TH/TH- (89).mp3
    - assets/sound/TH/TH- (90).mp3
    - assets/sound/TH/TH- (91).mp3
    - assets/sound/TH/TH- (92).mp3
    - assets/sound/TH/TH- (93).mp3
    - assets/sound/TH/TH- (94).mp3
    - assets/sound/TH/TH- (95).mp3
    - assets/sound/TH/TH- (96).mp3
    - assets/sound/TH/TH- (97).mp3
    - assets/sound/TH/TH- (98).mp3
    - assets/sound/TH/TH- (99).mp3
    - assets/sound/TH/
    - assets/sound/CN/
    - assets/sound/
    - assets/sound/TH/
    - assets/sound/EN/
    - assets/images/
    - assets/images/logoapp.jpg
    - assets/images/Slide1.jpg
    - assets/images/Slide2.jpg
    - assets/images/Slide3.jpg
    - assets/images/Slide4.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gymno
      fonts:
        - asset: fonts/Gymno.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: SukhumvitSet
      fonts:
        - asset: fonts/SukhumvitSet-Bold.ttf
    - family: DM
      fonts:
        - asset: fonts/LED.ttf
    - family: DIGITAL
      fonts:
        - asset: fonts/digital.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
